<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>L2Dn.NpcBrain</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="L2Dn.Npc.Brain.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\L2Dn.Npc.Contracts\L2Dn.Npc.Contracts.csproj" />
  </ItemGroup>

</Project>
