[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..\..')).Path
$dataPack = Join-Path $repoRoot 'L2Dn\L2Dn.GameServer\DataPack'
$outputPath = Join-Path $dataPack 'LimitShopCraft.xml'

$itemNames = @{}
Get-ChildItem -LiteralPath (Join-Path $dataPack 'stats\items') -Filter '*.xml' | ForEach-Object {
    $document = [xml](Get-Content -LiteralPath $_.FullName -Raw)
    foreach ($item in $document.list.item) {
        if ($null -ne $item.id -and $null -ne $item.name) {
            $itemNames[[int]$item.id] = [string]$item.name
        }
    }
}

function Get-ItemName([int]$itemId) {
    if (-not $itemNames.ContainsKey($itemId)) {
        throw "Item $itemId is not defined in the server datapack."
    }

    return $itemNames[$itemId]
}

function New-Ingredient([int]$id, [long]$count, [Nullable[int]]$enchant = $null) {
    return [pscustomobject]@{ Id = $id; Count = $count; Enchant = $enchant }
}

$lines = [System.Collections.Generic.List[string]]::new()
function Add-Line([string]$line = '') {
    $lines.Add($line)
}

function Add-Product(
    [int]$id,
    [int]$category,
    [object[]]$ingredients,
    [System.Collections.IDictionary]$production) {
    Add-Line "`t<product id=`"$id`" category=`"$category`">"
    foreach ($ingredient in $ingredients) {
        $enchant = if ($null -ne $ingredient.Enchant) { " enchant=`"$($ingredient.Enchant)`"" } else { '' }
        Add-Line "`t`t<ingredient id=`"$($ingredient.Id)`" count=`"$($ingredient.Count)`"$enchant /> <!-- $(Get-ItemName $ingredient.Id) -->"
    }

    $attributes = foreach ($entry in $production.GetEnumerator()) {
        "$($entry.Key)=`"$($entry.Value)`""
    }
    Add-Line "`t`t<production $($attributes -join ' ') /> <!-- $(Get-ItemName ([int]$production.id)) -->"
    Add-Line "`t</product>"
}

Add-Line '<?xml version="1.0" encoding="UTF-8"?>'
Add-Line '<list enabled="true" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/LimitShop.xsd">'
Add-Line "`t<!-- Generated by tools/server/Build-ClassicSpecialCraftCatalog.ps1. -->"
Add-Line "`t<!-- Categories: 0 Special Weapon, 2 Spellbook, 3 Accessories, 4 Misc, 5 Blessing, 6 Event. -->"
Add-Line
Add-Line "`t<!-- Category 0: deterministic Frost Lord weapon progression. -->"

$frostWeapons = @(
    95823, 95824, 95825, 95826, 95827, 95828,
    95829, 95830, 95831, 95832, 95833, 95835
)
$frostProductIds = @(1542..1552) + 1554
if ($frostProductIds.Count -ne $frostWeapons.Count) {
    throw "Frost weapon ProductId count ($($frostProductIds.Count)) does not match weapon count ($($frostWeapons.Count))."
}

for ($index = 0; $index -lt $frostWeapons.Count; $index++) {
    Add-Product -id $frostProductIds[$index] -category 0 -ingredients @(
        (New-Ingredient 95781 1),
        (New-Ingredient 95782 1500)
    ) -production ([ordered]@{ id = $frostWeapons[$index] })
}

Add-Line
Add-Line "`t<!-- Category 2: all third-class books that are consumed by the active skill trees. -->"
$spellbookIds = @(90046..90135 | Where-Object { $_ -notin @(90052, 90074, 90132) })
$spellbookProductIds = @(
    4238..4245
    4521..4524
    4767, 4768, 4870, 4871
    3591..3661
)
if ($spellbookProductIds.Count -ne $spellbookIds.Count) {
    throw "Spellbook ProductId count ($($spellbookProductIds.Count)) does not match book count ($($spellbookIds.Count))."
}

for ($index = 0; $index -lt $spellbookIds.Count; $index++) {
    Add-Product -id $spellbookProductIds[$index] -category 2 -ingredients @(
        (New-Ingredient 90045 31),
        (New-Ingredient 57 100000)
    ) -production ([ordered]@{ id = $spellbookIds[$index] })
}

Add-Line
Add-Line "`t<!-- Category 3: seven complete raid-accessory upgrade chains. -->"
$accessoryFamilies = @(
    [pscustomobject]@{ Name = 'Frintezza'; Base = 91550; Levels = @(91551, 91552, 91553, 99228); Rate = 4; Fee = 300000000 },
    [pscustomobject]@{ Name = 'Antharas'; Base = 90992; Levels = @(91138, 91139, 91383, 99227); Rate = 4; Fee = 300000000 },
    [pscustomobject]@{ Name = 'Baium'; Base = 49580; Levels = @(49581, 49582, 91381, 99225); Rate = 3; Fee = 300000000 },
    [pscustomobject]@{ Name = 'Zaken'; Base = 90763; Levels = @(90764, 90765, 91382, 99226); Rate = 3; Fee = 150000000 },
    [pscustomobject]@{ Name = 'Queen Ant'; Base = 6660; Levels = @(49574, 49577, 91378, 99222); Rate = 3; Fee = 150000000 },
    [pscustomobject]@{ Name = 'Orfen'; Base = 6661; Levels = @(49575, 49578, 91379, 99223); Rate = 3; Fee = 150000000 },
    [pscustomobject]@{ Name = 'Core'; Base = 6662; Levels = @(49576, 49579, 91380, 99224); Rate = 3; Fee = 150000000 }
)
$accessoryProductIds = @(4353..4378) + @(4381, 4382)
if ($accessoryProductIds.Count -ne ($accessoryFamilies.Count * 4)) {
    throw "Accessory ProductId count ($($accessoryProductIds.Count)) does not match recipe count ($($accessoryFamilies.Count * 4))."
}

for ($familyIndex = 0; $familyIndex -lt $accessoryFamilies.Count; $familyIndex++) {
    $family = $accessoryFamilies[$familyIndex]
    $productIds = $accessoryProductIds[($familyIndex * 4)..(($familyIndex * 4) + 3)]
    Add-Product -id $productIds[0] -category 3 -ingredients @(
        (New-Ingredient $family.Base 2),
        (New-Ingredient 57 5000000)
    ) -production ([ordered]@{ id = $family.Levels[0] })

    Add-Product -id $productIds[1] -category 3 -ingredients @(
        (New-Ingredient $family.Levels[0] 2),
        (New-Ingredient 57 20000000)
    ) -production ([ordered]@{ id = $family.Levels[1] })

    Add-Product -id $productIds[2] -category 3 -ingredients @(
        (New-Ingredient $family.Levels[1] 2),
        (New-Ingredient 57 100000000)
    ) -production ([ordered]@{ id = $family.Levels[2] })

    Add-Product -id $productIds[3] -category 3 -ingredients @(
        (New-Ingredient $family.Levels[2] 1),
        (New-Ingredient $family.Base 1),
        (New-Ingredient 57 $family.Fee)
    ) -production ([ordered]@{
        id = $family.Levels[3]
        chance = $family.Rate
        id2 = $family.Levels[2]
        count2 = 1
        chance2 = 100 - $family.Rate
        refundAdenaOnFailure = 'true'
    })
}

Add-Line
Add-Line "`t<!-- Category 4: tablets, permanent progression materials and augmenting-stone conversions. -->"
Add-Product -id 3662 -category 4 -ingredients @((New-Ingredient 91040 20), (New-Ingredient 57 200000)) -production ([ordered]@{ id = 90045 })
Add-Product -id 3663 -category 4 -ingredients @((New-Ingredient 91039 20), (New-Ingredient 57 200000)) -production ([ordered]@{ id = 90045 })
Add-Product -id 3664 -category 4 -ingredients @((New-Ingredient 91041 20), (New-Ingredient 57 200000)) -production ([ordered]@{ id = 90045 })
Add-Product -id 3665 -category 4 -ingredients @((New-Ingredient 91042 20), (New-Ingredient 57 200000)) -production ([ordered]@{ id = 90045 })

Add-Product -id 1112 -category 4 -ingredients @((New-Ingredient 94328 10)) -production ([ordered]@{
    id = 94314; chance = 5; id2 = 94328; count2 = 7; chance2 = 95
})
Add-Product -id 1878 -category 4 -ingredients @((New-Ingredient 96623 5), (New-Ingredient 57 500000)) -production ([ordered]@{
    id = 96630; count = 3; chance = 8; id2 = 96630; count2 = 1; chance2 = 67; id3 = 96623; count3 = 2; chance3 = 25
})

$augmentingRecipes = @(
    @(3350, 97787, 97789), @(3351, 97788, 97790),
    @(3352, 94186, 97439), @(3353, 94210, 97444),
    @(3354, 94188, 97440), @(3355, 94212, 97445),
    @(3356, 94423, 97442), @(3357, 94424, 97447)
)
foreach ($recipe in $augmentingRecipes) {
    Add-Product -id $recipe[0] -category 4 -ingredients @(
        (New-Ingredient $recipe[1] 2),
        (New-Ingredient 57 1000000)
    ) -production ([ordered]@{
        id = $recipe[2]; chance = 15; id2 = $recipe[1]; count2 = 1; chance2 = 85
    })
}

Add-Product -id 4267 -category 4 -ingredients @(
    (New-Ingredient 94384 5),
    (New-Ingredient 91663 1000),
    (New-Ingredient 57 10000000)
) -production ([ordered]@{ id = 97860 })

Add-Line
Add-Line "`t<!-- Category 5: deterministic +4 through +10 blessing conversions. -->"
$blessingFamilies = @(
    [pscustomobject]@{ Product = 1203; Base = 91862; Output = 94621; OutputEnchant = $true },
    [pscustomobject]@{ Product = 2879; Base = 92403; Output = 97563; OutputEnchant = $false },
    [pscustomobject]@{ Product = 2886; Base = 92018; Output = 97573; OutputEnchant = $false },
    [pscustomobject]@{ Product = 3701; Base = 94166; Output = 98205; OutputEnchant = $true },
    [pscustomobject]@{ Product = 4009; Base = 91061; Output = 98713; OutputEnchant = $false },
    [pscustomobject]@{ Product = 4182; Base = 91745; Output = 98723; OutputEnchant = $false }
)
foreach ($family in $blessingFamilies) {
    foreach ($enchant in 4..10) {
        $outputId = if ($family.OutputEnchant) { $family.Output } else { $family.Output + $enchant - 4 }
        $production = [ordered]@{ id = $outputId }
        if ($family.OutputEnchant) {
            $production.enchant = $enchant
        }

        Add-Product -id ($family.Product + $enchant - 4) -category 5 -ingredients @(
            (New-Ingredient $family.Base 2 $enchant)
        ) -production $production
    }
}

Add-Line
Add-Line "`t<!-- Category 6 intentionally remains empty until a dated event is active. -->"
Add-Line '</list>'

$encoding = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllLines($outputPath, $lines, $encoding)
Write-Host "Generated $outputPath with $($frostWeapons.Count + $spellbookIds.Count + ($accessoryFamilies.Count * 4) + 15 + ($blessingFamilies.Count * 7)) recipes."
